first commit
mate-academy/jv-lambda-calc pull request #148
Opened 2020-12-23 11:53 UTC by RuslanIbIsh

2020-12-23 12:14 UTC, Resci requested changes

2020-12-23 12:14 UTC, Resci commented on src/main/java/core/basesyntax/CalculatorImpl.java
> + */
```suggestion
```

2020-12-23 12:14 UTC, Resci commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        }
Repeated part of the code need move separate method

2020-12-23 12:14 UTC, Resci commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        }
What about 
`firstNumeric == Double.MAX_VALUE && secondNumeric == Double.MAX_VALUE - 1`
?

2020-12-23 12:14 UTC, Resci commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +        assertThrows(RuntimeException.class, () -> {
Why not a AriphmeticException?

2020-12-23 12:29 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/CalculatorImpl.java
> + */
removed ))

2020-12-23 12:30 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        }
added or operator

second question - just ask the mentor on QA

2020-12-23 12:33 UTC, RuslanIbIsh commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +        assertThrows(RuntimeException.class, () -> {
you are right about more specific exception

2020-12-23 14:14 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        }
@Resci  
 `Double.MAX_VALUE + (Double.MAX_VALUE - 1)` Also be an Infinity, or what did you ask?

2020-12-23 14:38 UTC, dmytro-hryhoruk requested changes

2020-12-23 14:38 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        if (firstNumeric == Double.MAX_VALUE && secondNumeric == Double.MAX_VALUE) {
what if firstNumeric = Double.MAX_VALUE, but second = secondNumeric =2?
Now I can see that's there is a lot of cases not covered by this solution. I recommend you to use Double.isFinite() or Double.isInfinite() method to check the results. This would be simpler

2020-12-23 14:38 UTC, dmytro-hryhoruk commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +class CalculatorImplTest {
let's add more test cases:
- addition with 2 negative operands
- addition with positive and negative operands
- addition with zero in different places
- addition for min double values
- same for subtraction
- same for multiplication
-  raising negative value to positive power
- raising positive/negative value to negative power
- raising positive/negative value to zero power

-

2020-12-23 17:04 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        if (firstNumeric == Double.MAX_VALUE && secondNumeric == Double.MAX_VALUE) {
I change my logic

2020-12-23 17:04 UTC, RuslanIbIsh commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +class CalculatorImplTest {
done

2020-12-24 11:41 UTC, dmytro-hryhoruk approved these changes

2026-01-07 16:18 UTC, closed without merging