added first solution... or test to solution... nvm
mate-academy/jv-lambda-calc pull request #174
Opened 2021-04-18 19:32 UTC by IhorRome

2021-04-19 09:32 UTC, andriiromaniuk requested changes

2021-04-19 09:32 UTC, andriiromaniuk commented on src/main/java/core/basesyntax/Calculator.java
> +                    throw new ArithmeticException();
ArithmeticException is exception which is throwed when we try to do something that math itself forbids, this is not the case.

2021-04-19 09:32 UTC, andriiromaniuk commented on src/main/java/core/basesyntax/exception/NullDivisorException.java
> +public class NullDivisorException extends RuntimeException {
just use arithmetic, this is the case.

2021-04-19 09:32 UTC, andriiromaniuk commented on src/main/java/core/basesyntax/exception/InvalidOperatorException.java
> +public class InvalidOperatorException extends RuntimeException {
UnsupportedOperationException also exists

2021-04-19 09:37 UTC, andriiromaniuk requested changes

2021-04-19 09:37 UTC, andriiromaniuk commented on src/test/java/core/basesyntax/CalculatorTest.java
> +        assertEquals(expected, actual);
You are testing half of your code with one Unit(!) test, make it different tests.

2021-04-20 11:05 UTC, andriiromaniuk approved these changes

2021-04-21 09:29 UTC, Max-Pochepets requested changes

2021-04-21 09:29 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/Calculator.java
> +                if (result >= Double.MAX_VALUE || result <= -Double.MAX_VALUE) {
this is overthinking. besides, there is no such thing as ValueLimit, you'll get positive or negative infinity. we don't need this check

2021-04-21 15:01 UTC, Max-Pochepets requested changes

2021-04-21 15:01 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/Calculator.java
> +                if (result >= Double.MAX_VALUE || result <= -Double.MAX_VALUE) {
what about this?

2021-04-22 07:37 UTC, Max-Pochepets approved these changes

2024-10-14 09:11 UTC, closed without merging