created tests for CalculatorImpl
mate-academy/jv-lambda-calc pull request #228
Opened 2021-06-24 14:05 UTC by Daniel1004K

2021-06-24 14:30 UTC, Tamara-Paskalova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +    }
In my opinion it's better to make the values of operation characters constant.

2021-06-24 14:30 UTC, Tamara-Paskalova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +    }
In my opinion last part of this test is quite enough. The loop is redundant

2021-06-24 14:30 UTC, Tamara-Paskalova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +                calculator.calculate(34, 53, (char) i);
It's hard for me to understand what are you doing here

2021-06-24 15:21 UTC, Daniel1004K commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +    }
I think so

2021-06-25 06:07 UTC, Tamara-Paskalova approved these changes

2021-06-25 06:08 UTC, Tamara-Paskalova approved these changes
Good job!

2021-06-25 06:50 UTC, KseniiaMakarova requested changes
an interesting solution, nice job!

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +
redundant empty line

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +    public static final String CHARACTER = "[+/*^]|--";
```suggestion
    public static final String NUMBER_REGEX = "-?\\d+\\.?\\d+|-?\\d+";
    public static final String CHARACTER_REGEX = "[+/*^]|--";
```

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        throw new IllegalArgumentException("Not defined function");
let's better use switch case

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +    public double div(double a, double b) {
```suggestion
    public double divide(double a, double b) {
```

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +    public double pow(double a, double power) {
```suggestion
    public double power(double a, double power) {
```

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +            throw new IllegalArgumentException();
let's add informative message here

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        throw new IllegalArgumentException();
same

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        throw new IllegalArgumentException();
same

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +    private static final double DELTA = 0.0001;
let's switch these 2 lines - constants should be declared above other fields

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +            for (int character = 0; character < 1000; character++) {
this seems to take the first available char that is not suitable, call calculate(), get the exception, and it is over - we won't go further in the loop

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +                assertEquals(i - j, calculator.calculate(i + " -- " + j), DELTA,
why `--`?

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +        assertEquals(35.56 - 30.56, calculator.calculate(35.56 + " -- " + 30.56), DELTA);
same

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +                }
why do we skip 0?

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +                assertEquals((double) i * j, calculator.calculate(i + " * " + j), DELTA,
```suggestion
                assertEquals(i * j, calculator.calculate(i + " * " + j), DELTA,
```

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +                }
why do we skip 0?

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +    }
please move this method to the beginning of the class

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +        );
```suggestion
        double actual = calculator.calculate(a, b, PLUS);
```

2021-06-25 06:50 UTC, KseniiaMakarova commented on src/test/java/core/basesyntax/CalculatorImplTest.java
> +        assertThrows(IllegalArgumentException.class, () -> {
this seems to take the first available char that is not suitable, call calculate(), get the exception, and it is over - we won't go further in the loop

2021-06-29 09:01 UTC, Sofasmile requested changes

2021-06-29 09:36 UTC, Sofasmile approved these changes

2021-06-29 09:36 UTC, Sofasmile commented on src/main/java/core/basesyntax/CalculatorImpl.java
> +        throw new IllegalArgumentException("Input expression is wrong.");
```suggestion
        throw new IllegalArgumentException("Input expression - " + expression +" is wrong.");
```
same everywhere

2023-04-07 12:42 UTC, closed without merging