added jv-lambda-calculator solution
mate-academy/jv-lambda-calc pull request #236
Opened 2021-06-27 16:32 UTC by Basilius-Third

2021-06-27 17:20 UTC, aaananas requested changes

2021-06-27 17:20 UTC, aaananas commented on src/main/java/core/basesyntax/Calculator.java
> +                break;
Можна одразу повертати значення
```suggestion
                return firstOperand + secondOperand;
              
```

2021-06-27 17:20 UTC, aaananas commented on src/main/java/core/basesyntax/Calculator.java
> +                break;
```suggestion
                return Math.pow(firstOperand, secondOperand);
```

2021-06-27 17:20 UTC, aaananas commented on src/main/java/core/basesyntax/Calculator.java
> +                result = firstOperand / secondOperand;
коли ділимо на 0, потрібно викидати ексепшин

2021-06-27 17:20 UTC, aaananas commented on src/main/java/core/basesyntax/NoSuchOperationException.java
> +
Непотрібна пуста строка

2021-06-27 17:20 UTC, aaananas commented on src/test/java/core/basesyntax/CalculatorTest.java
> +        assertEquals(expected, actual, DELTA);
```suggestion
        assertThrows(ArithmeticException.class,
                () -> calculator.calculate(15, 0, '/'))
```

2021-06-27 17:24 UTC, Basilius-Third commented on src/main/java/core/basesyntax/Calculator.java
> +                break;
А шо нельзя так? Не хотел подтягивать Math к моему классу

2021-06-27 17:26 UTC, aaananas commented on src/main/java/core/basesyntax/Calculator.java
> +                break;
та можна, але тут калькулятор для double, а метод Math.pow якраз для double, та і з 10 лінійок до 1 зменшиться код

2021-06-27 17:42 UTC, aaananas approved these changes

2021-06-29 08:27 UTC, Sofasmile requested changes

2021-06-29 08:27 UTC, Sofasmile commented on src/main/java/core/basesyntax/Calculator.java
> +            case '+':
if you want you can create constants for operators

2021-06-29 08:27 UTC, Sofasmile commented on src/test/java/core/basesyntax/CalculatorTest.java
> +    private double actual;
we shouldn't move expected and actual variables to the class. It is better to return them to the methods where we use them

2021-06-29 08:27 UTC, Sofasmile commented on src/test/java/core/basesyntax/CalculatorTest.java
> +        expected = 15d + 20d;
we can set the result value for a variable without adding two values (this comment is optional)
```suggestion
        expected = 35d;
```

2021-06-29 09:34 UTC, Sofasmile approved these changes

2021-11-16 17:08 UTC, closed without merging